apiVersion: v1
kind: Service
metadata:
  name: handcarry-postgresql
  labels:
    app: handcarry
spec:
  ports:
    - port: 5432
  selector:
    app: handcarry
    tier: db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim
  labels:
    app: handcarry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: handcarry-postgresql
  labels:
    app: handcarry
spec:
  selector:
    matchLabels:
      app: handcarry
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: handcarry
        tier: db
    spec:
      containers:
      - image: postgres:9.6.13
        name: postgresql
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-pass
              key: password
        - name: POSTGRES_USER
          value: handcarry
        - name: POSTGRES_DB
          value: handcarry
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/pgsql
      volumes:
      - name: postgresql-persistent-storage
        persistentVolumeClaim:
          claimName: postgresql-pv-claim
